import { Ayah } from '../types/quran';

// ============ Types ============

export interface VisualElement {
  emoji: string;
  ionicon: string;
  color: string;
  label: string;
  priority: number;
  category: string;
}

export interface AnchorWord {
  arabic: string;
  transliteration: string;
  meaning: string;
}

export interface AyahScene {
  elements: VisualElement[];
  dominantColor: string;
  accentColor: string;
  anchorWords: AnchorWord[];
  sceneSummary: string;
}

// ============ Unique Icon Pool ============
// 286 unique icons — one per ayah, enough for Surah Al-Baqarah (the longest surah)
// No rainbow, no anti-Islamic symbols. All appropriate for a Quran learning app.

const UNIQUE_ICONS: { emoji: string; ionicon: string; color: string; label: string }[] = [
  // 1–20: Divine & Spiritual
  { emoji: '\u2728', ionicon: 'sparkles', color: '#D4AF37', label: 'Divine' },
  { emoji: '\uD83D\uDC9A', ionicon: 'heart', color: '#10b981', label: 'Mercy' },
  { emoji: '\uD83E\uDDED', ionicon: 'compass-outline', color: '#10b981', label: 'Guidance' },
  { emoji: '\uD83D\uDC51', ionicon: 'ribbon-outline', color: '#D4AF37', label: 'Sovereign' },
  { emoji: '\uD83E\uDD32', ionicon: 'hand-left-outline', color: '#14b8a6', label: 'Worship' },
  { emoji: '\uD83D\uDE4F', ionicon: 'happy-outline', color: '#D4AF37', label: 'Praise' },
  { emoji: '\uD83D\uDD4C', ionicon: 'moon-outline', color: '#14b8a6', label: 'Faith' },
  { emoji: '\uD83D\uDD4A\uFE0F', ionicon: 'heart-outline', color: '#f5f5f0', label: 'Peace' },
  { emoji: '\uD83D\uDCDC', ionicon: 'person-circle-outline', color: '#D4AF37', label: 'Prophet' },
  { emoji: '\uD83D\uDE4C', ionicon: 'person-outline', color: '#10b981', label: 'Believer' },
  { emoji: '\u2705', ionicon: 'checkmark-circle-outline', color: '#10b981', label: 'Truth' },
  { emoji: '\uD83E\uDD4D', ionicon: 'heart-half-outline', color: '#34d399', label: 'Forgive' },
  { emoji: '\uD83E\uDEA8', ionicon: 'time-outline', color: '#14b8a6', label: 'Patience' },
  { emoji: '\uD83E\uDD1D', ionicon: 'handshake-outline', color: '#14b8a6', label: 'Covenant' },
  { emoji: '\uD83D\uDCA0', ionicon: 'diamond-outline', color: '#a855f7', label: 'Wisdom' },
  { emoji: '\uD83D\uDEE1\uFE0F', ionicon: 'shield-checkmark-outline', color: '#3b82f6', label: 'Refuge' },
  { emoji: '\uD83C\uDF81', ionicon: 'gift-outline', color: '#10b981', label: 'Reward' },
  { emoji: '\u2696\uFE0F', ionicon: 'scale-outline', color: '#f59e0b', label: 'Justice' },
  { emoji: '\uD83D\uDCB0', ionicon: 'cash-outline', color: '#fbbf24', label: 'Charity' },
  { emoji: '\uD83D\uDC65', ionicon: 'people-outline', color: '#a3a398', label: 'People' },
  // 21–50: Celestial & Sky
  { emoji: '\u2600\uFE0F', ionicon: 'sunny-outline', color: '#fb923c', label: 'Sun' },
  { emoji: '\uD83C\uDF19', ionicon: 'moon-outline', color: '#a3a398', label: 'Moon' },
  { emoji: '\u2B50', ionicon: 'star-outline', color: '#fbbf24', label: 'Star' },
  { emoji: '\uD83C\uDF0C', ionicon: 'cloudy-night-outline', color: '#3b82f6', label: 'Sky' },
  { emoji: '\uD83C\uDF03', ionicon: 'moon', color: '#6366f1', label: 'Night' },
  { emoji: '\uD83C\uDF05', ionicon: 'partly-sunny-outline', color: '#f59e0b', label: 'Dawn' },
  { emoji: '\u2601\uFE0F', ionicon: 'cloud-outline', color: '#94a3b8', label: 'Cloud' },
  { emoji: '\u26A1', ionicon: 'thunderstorm-outline', color: '#ef4444', label: 'Thunder' },
  { emoji: '\uD83C\uDF24\uFE0F', ionicon: 'sunny-outline', color: '#fbbf24', label: 'Daybreak' },
  { emoji: '\uD83C\uDF04', ionicon: 'sunny', color: '#fb923c', label: 'Sunrise' },
  { emoji: '\uD83C\uDF06', ionicon: 'moon-outline', color: '#6366f1', label: 'Dusk' },
  { emoji: '\uD83C\uDF0E', ionicon: 'globe-outline', color: '#3b82f6', label: 'World' },
  { emoji: '\uD83C\uDF11', ionicon: 'moon', color: '#334155', label: 'New Moon' },
  { emoji: '\uD83C\uDF15', ionicon: 'moon', color: '#fbbf24', label: 'Full Moon' },
  { emoji: '\uD83C\uDF1E', ionicon: 'sunny', color: '#fb923c', label: 'Bright Sun' },
  { emoji: '\u2604\uFE0F', ionicon: 'flash-outline', color: '#ef4444', label: 'Comet' },
  { emoji: '\uD83C\uDF20', ionicon: 'star', color: '#fbbf24', label: 'Shooting Star' },
  { emoji: '\uD83C\uDF0F', ionicon: 'earth-outline', color: '#22c55e', label: 'Globe' },
  { emoji: '\uD83C\uDF25\uFE0F', ionicon: 'cloud-outline', color: '#94a3b8', label: 'Overcast' },
  { emoji: '\uD83C\uDF26\uFE0F', ionicon: 'partly-sunny-outline', color: '#fbbf24', label: 'Partly Sun' },
  // 51–90: Nature & Earth
  { emoji: '\uD83C\uDF0D', ionicon: 'earth-outline', color: '#84cc16', label: 'Earth' },
  { emoji: '\u26F0\uFE0F', ionicon: 'triangle-outline', color: '#78716c', label: 'Mountain' },
  { emoji: '\uD83D\uDCA7', ionicon: 'water-outline', color: '#06b6d4', label: 'Water' },
  { emoji: '\uD83C\uDF33', ionicon: 'leaf-outline', color: '#22c55e', label: 'Tree' },
  { emoji: '\uD83D\uDD25', ionicon: 'flame-outline', color: '#ef4444', label: 'Fire' },
  { emoji: '\uD83C\uDF2C\uFE0F', ionicon: 'leaf-outline', color: '#94a3b8', label: 'Wind' },
  { emoji: '\uD83C\uDF3F', ionicon: 'leaf-outline', color: '#22c55e', label: 'Sprout' },
  { emoji: '\uD83C\uDF0A', ionicon: 'water-outline', color: '#3b82f6', label: 'Wave' },
  { emoji: '\uD83C\uDF3E', ionicon: 'leaf-outline', color: '#D4AF37', label: 'Harvest' },
  { emoji: '\uD83C\uDF31', ionicon: 'leaf-outline', color: '#22c55e', label: 'Seedling' },
  { emoji: '\uD83C\uDF32', ionicon: 'leaf-outline', color: '#166534', label: 'Evergreen' },
  { emoji: '\uD83C\uDF34', ionicon: 'leaf-outline', color: '#84cc16', label: 'Palm' },
  { emoji: '\uD83C\uDF35', ionicon: 'leaf-outline', color: '#22c55e', label: 'Desert' },
  { emoji: '\uD83C\uDF37', ionicon: 'flower-outline', color: '#f43e5e', label: 'Bloom' },
  { emoji: '\uD83C\uDF39', ionicon: 'flower-outline', color: '#ef4444', label: 'Rose' },
  { emoji: '\uD83C\uDF3A', ionicon: 'flower-outline', color: '#fb923c', label: 'Flower' },
  { emoji: '\uD83C\uDF3B', ionicon: 'sunny-outline', color: '#fbbf24', label: 'Sunflower' },
  { emoji: '\uD83C\uDF3C', ionicon: 'flower-outline', color: '#f5f5f0', label: 'Blossom' },
  { emoji: '\uD83C\uDF40', ionicon: 'leaf-outline', color: '#10b981', label: 'Clover' },
  { emoji: '\uD83C\uDF41', ionicon: 'leaf-outline', color: '#fb923c', label: 'Leaf' },
  { emoji: '\uD83C\uDF42', ionicon: 'leaf-outline', color: '#78716c', label: 'Fallen Leaf' },
  { emoji: '\uD83C\uDF43', ionicon: 'leaf-outline', color: '#84cc16', label: 'Leaves' },
  { emoji: '\uD83C\uDF44', ionicon: 'nutrition-outline', color: '#ef4444', label: 'Mushroom' },
  { emoji: '\uD83E\uDEB4', ionicon: 'leaf-outline', color: '#22c55e', label: 'Plant' },
  { emoji: '\uD83C\uDF4E', ionicon: 'nutrition-outline', color: '#ef4444', label: 'Fruit' },
  { emoji: '\uD83C\uDF47', ionicon: 'nutrition-outline', color: '#a855f7', label: 'Grape' },
  { emoji: '\uD83C\uDF4A', ionicon: 'nutrition-outline', color: '#fb923c', label: 'Orange' },
  { emoji: '\uD83C\uDF4B', ionicon: 'nutrition-outline', color: '#fbbf24', label: 'Lemon' },
  { emoji: '\uD83C\uDF4C', ionicon: 'nutrition-outline', color: '#fbbf24', label: 'Banana' },
  { emoji: '\uD83C\uDF52', ionicon: 'nutrition-outline', color: '#ef4444', label: 'Cherry' },
  { emoji: '\uD83C\uDF53', ionicon: 'nutrition-outline', color: '#f43e5e', label: 'Berry' },
  { emoji: '\uD83C\uDF45', ionicon: 'nutrition-outline', color: '#ef4444', label: 'Tomato' },
  { emoji: '\uD83C\uDF3D', ionicon: 'nutrition-outline', color: '#fbbf24', label: 'Corn' },
  { emoji: '\uD83E\uDD55', ionicon: 'nutrition-outline', color: '#fb923c', label: 'Carrot' },
  { emoji: '\uD83C\uDF36\uFE0F', ionicon: 'flame-outline', color: '#ef4444', label: 'Pepper' },
  { emoji: '\uD83E\uDD51', ionicon: 'nutrition-outline', color: '#84cc16', label: 'Avocado' },
  { emoji: '\uD83C\uDF4D', ionicon: 'nutrition-outline', color: '#fbbf24', label: 'Pineapple' },
  { emoji: '\uD83E\uDED2', ionicon: 'nutrition-outline', color: '#22c55e', label: 'Olive' },
  { emoji: '\uD83C\uDF4F', ionicon: 'nutrition-outline', color: '#22c55e', label: 'Green Apple' },
  { emoji: '\uD83C\uDF48', ionicon: 'nutrition-outline', color: '#22c55e', label: 'Melon' },
  // 91–130: Animals
  { emoji: '\uD83D\uDC26', ionicon: 'paw-outline', color: '#a3a398', label: 'Bird' },
  { emoji: '\uD83D\uDC2B', ionicon: 'paw-outline', color: '#D4AF37', label: 'Camel' },
  { emoji: '\uD83D\uDC1D', ionicon: 'paw-outline', color: '#fbbf24', label: 'Bee' },
  { emoji: '\uD83D\uDC1C', ionicon: 'paw-outline', color: '#78716c', label: 'Ant' },
  { emoji: '\uD83D\uDD77\uFE0F', ionicon: 'paw-outline', color: '#334155', label: 'Spider' },
  { emoji: '\uD83D\uDC0B', ionicon: 'fish-outline', color: '#3b82f6', label: 'Whale' },
  { emoji: '\uD83D\uDC1F', ionicon: 'fish-outline', color: '#06b6d4', label: 'Fish' },
  { emoji: '\uD83D\uDC18', ionicon: 'paw-outline', color: '#94a3b8', label: 'Elephant' },
  { emoji: '\uD83D\uDC06', ionicon: 'paw-outline', color: '#fbbf24', label: 'Leopard' },
  { emoji: '\uD83E\uDD81', ionicon: 'paw-outline', color: '#D4AF37', label: 'Lion' },
  { emoji: '\uD83D\uDC0E', ionicon: 'paw-outline', color: '#78716c', label: 'Horse' },
  { emoji: '\uD83D\uDC11', ionicon: 'paw-outline', color: '#f5f5f0', label: 'Sheep' },
  { emoji: '\uD83D\uDC02', ionicon: 'paw-outline', color: '#78716c', label: 'Ox' },
  { emoji: '\uD83E\uDD85', ionicon: 'paw-outline', color: '#D4AF37', label: 'Eagle' },
  { emoji: '\uD83D\uDC0A', ionicon: 'paw-outline', color: '#22c55e', label: 'Croc' },
  { emoji: '\uD83E\uDD89', ionicon: 'paw-outline', color: '#6366f1', label: 'Owl' },
  { emoji: '\uD83D\uDC22', ionicon: 'paw-outline', color: '#22c55e', label: 'Turtle' },
  { emoji: '\uD83E\uDD8B', ionicon: 'paw-outline', color: '#fb923c', label: 'Butterfly' },
  { emoji: '\uD83D\uDC1B', ionicon: 'paw-outline', color: '#22c55e', label: 'Caterpillar' },
  { emoji: '\uD83D\uDC20', ionicon: 'fish-outline', color: '#fbbf24', label: 'Tropical Fish' },
  { emoji: '\uD83D\uDC21', ionicon: 'fish-outline', color: '#fb923c', label: 'Blowfish' },
  { emoji: '\uD83E\uDD86', ionicon: 'paw-outline', color: '#84cc16', label: 'Duck' },
  { emoji: '\uD83E\uDD9A', ionicon: 'paw-outline', color: '#14b8a6', label: 'Peacock' },
  { emoji: '\uD83D\uDC0D', ionicon: 'paw-outline', color: '#22c55e', label: 'Serpent' },
  { emoji: '\uD83E\uDD82', ionicon: 'paw-outline', color: '#ef4444', label: 'Scorpion' },
  { emoji: '\uD83D\uDC10', ionicon: 'paw-outline', color: '#f5f5f0', label: 'Goat' },
  { emoji: '\uD83D\uDC12', ionicon: 'paw-outline', color: '#78716c', label: 'Monkey' },
  { emoji: '\uD83E\uDD8C', ionicon: 'paw-outline', color: '#D4AF37', label: 'Deer' },
  { emoji: '\uD83D\uDC13', ionicon: 'paw-outline', color: '#ef4444', label: 'Rooster' },
  { emoji: '\uD83D\uDC23', ionicon: 'paw-outline', color: '#fbbf24', label: 'Chick' },
  { emoji: '\uD83D\uDC2A', ionicon: 'paw-outline', color: '#D4AF37', label: 'Dromedary' },
  { emoji: '\uD83E\uDD8D', ionicon: 'paw-outline', color: '#334155', label: 'Gorilla' },
  { emoji: '\uD83D\uDC03', ionicon: 'paw-outline', color: '#78716c', label: 'Buffalo' },
  { emoji: '\uD83E\uDD9C', ionicon: 'paw-outline', color: '#22c55e', label: 'Parrot' },
  { emoji: '\uD83E\uDD83', ionicon: 'paw-outline', color: '#D4AF37', label: 'Turkey' },
  { emoji: '\uD83E\uDD9E', ionicon: 'fish-outline', color: '#ef4444', label: 'Lobster' },
  { emoji: '\uD83D\uDC19', ionicon: 'fish-outline', color: '#a855f7', label: 'Octopus' },
  { emoji: '\uD83D\uDC1A', ionicon: 'fish-outline', color: '#fb923c', label: 'Shell' },
  { emoji: '\uD83E\uDD80', ionicon: 'fish-outline', color: '#ef4444', label: 'Crab' },
  { emoji: '\uD83E\uDD88', ionicon: 'fish-outline', color: '#3b82f6', label: 'Shark' },
  // 131–170: Objects & Knowledge
  { emoji: '\uD83D\uDCD6', ionicon: 'book-outline', color: '#a855f7', label: 'Book' },
  { emoji: '\uD83D\uDCDA', ionicon: 'library-outline', color: '#a855f7', label: 'Library' },
  { emoji: '\uD83D\uDCDD', ionicon: 'create-outline', color: '#3b82f6', label: 'Writing' },
  { emoji: '\uD83D\uDD8A\uFE0F', ionicon: 'pencil-outline', color: '#6366f1', label: 'Pen' },
  { emoji: '\uD83D\uDCDC', ionicon: 'document-text-outline', color: '#D4AF37', label: 'Scroll' },
  { emoji: '\uD83D\uDD12', ionicon: 'lock-closed-outline', color: '#6366f1', label: 'Seal' },
  { emoji: '\uD83D\uDD13', ionicon: 'lock-open-outline', color: '#10b981', label: 'Unlock' },
  { emoji: '\uD83D\uDD11', ionicon: 'key-outline', color: '#D4AF37', label: 'Key' },
  { emoji: '\uD83E\uDDE0', ionicon: 'bulb-outline', color: '#a855f7', label: 'Mind' },
  { emoji: '\uD83D\uDCA1', ionicon: 'bulb-outline', color: '#fbbf24', label: 'Idea' },
  { emoji: '\uD83C\uDFDB\uFE0F', ionicon: 'business-outline', color: '#78716c', label: 'Pillar' },
  { emoji: '\uD83D\uDDE3\uFE0F', ionicon: 'megaphone-outline', color: '#fb923c', label: 'Voice' },
  { emoji: '\u23F3', ionicon: 'hourglass-outline', color: '#f59e0b', label: 'Time' },
  { emoji: '\u231A', ionicon: 'time-outline', color: '#3b82f6', label: 'Hour' },
  { emoji: '\uD83D\uDD14', ionicon: 'notifications-outline', color: '#D4AF37', label: 'Bell' },
  { emoji: '\uD83D\uDCE3', ionicon: 'megaphone-outline', color: '#ef4444', label: 'Call' },
  { emoji: '\uD83C\uDFA4', ionicon: 'mic-outline', color: '#a3a398', label: 'Recite' },
  { emoji: '\uD83C\uDFAF', ionicon: 'locate-outline', color: '#ef4444', label: 'Target' },
  { emoji: '\uD83D\uDD2D', ionicon: 'telescope-outline', color: '#6366f1', label: 'Observe' },
  { emoji: '\uD83D\uDD2C', ionicon: 'search-outline', color: '#3b82f6', label: 'Examine' },
  { emoji: '\u2709\uFE0F', ionicon: 'mail-outline', color: '#94a3b8', label: 'Message' },
  { emoji: '\uD83D\uDCE6', ionicon: 'cube-outline', color: '#78716c', label: 'Provision' },
  { emoji: '\uD83C\uDFF3\uFE0F', ionicon: 'flag-outline', color: '#f5f5f0', label: 'Banner' },
  { emoji: '\uD83C\uDFFA', ionicon: 'cafe-outline', color: '#D4AF37', label: 'Vessel' },
  { emoji: '\uD83D\uDD6F\uFE0F', ionicon: 'flame-outline', color: '#fb923c', label: 'Candle' },
  { emoji: '\uD83E\uDE94', ionicon: 'shield-outline', color: '#78716c', label: 'Armor' },
  { emoji: '\u2694\uFE0F', ionicon: 'flash-outline', color: '#94a3b8', label: 'Sword' },
  { emoji: '\uD83C\uDFF9', ionicon: 'flash-outline', color: '#ef4444', label: 'Bow' },
  { emoji: '\uD83D\uDEA2', ionicon: 'boat-outline', color: '#3b82f6', label: 'Ship' },
  { emoji: '\u2693', ionicon: 'boat-outline', color: '#334155', label: 'Anchor' },
  // 171–210: Actions & Concepts
  { emoji: '\uD83C\uDF1F', ionicon: 'color-wand-outline', color: '#f59e0b', label: 'Creation' },
  { emoji: '\uD83D\uDD2F', ionicon: 'sunny', color: '#f59e0b', label: 'Light' },
  { emoji: '\uD83D\uDCAB', ionicon: 'sparkles-outline', color: '#D4AF37', label: 'Glory' },
  { emoji: '\u2764\uFE0F', ionicon: 'heart', color: '#ef4444', label: 'Love' },
  { emoji: '\uD83D\uDD25', ionicon: 'bonfire-outline', color: '#fb923c', label: 'Blaze' },
  { emoji: '\uD83C\uDF27\uFE0F', ionicon: 'rainy-outline', color: '#3b82f6', label: 'Rain' },
  { emoji: '\u2744\uFE0F', ionicon: 'snow-outline', color: '#06b6d4', label: 'Snow' },
  { emoji: '\uD83C\uDF28\uFE0F', ionicon: 'thunderstorm-outline', color: '#94a3b8', label: 'Blizzard' },
  { emoji: '\uD83C\uDF29\uFE0F', ionicon: 'thunderstorm-outline', color: '#6366f1', label: 'Storm' },
  { emoji: '\uD83C\uDF2A\uFE0F', ionicon: 'flash-outline', color: '#94a3b8', label: 'Tornado' },
  { emoji: '\uD83C\uDF0B', ionicon: 'flame-outline', color: '#ef4444', label: 'Volcano' },
  { emoji: '\uD83C\uDF0A', ionicon: 'water', color: '#06b6d4', label: 'Flood' },
  { emoji: '\u26A0\uFE0F', ionicon: 'warning-outline', color: '#fb7185', label: 'Warning' },
  { emoji: '\uD83D\uDEAB', ionicon: 'close-circle-outline', color: '#ef4444', label: 'Forbid' },
  { emoji: '\u270B', ionicon: 'hand-left-outline', color: '#fbbf24', label: 'Stop' },
  { emoji: '\uD83D\uDCAA', ionicon: 'fitness-outline', color: '#fb923c', label: 'Strength' },
  { emoji: '\uD83D\uDC63', ionicon: 'footsteps-outline', color: '#78716c', label: 'Footsteps' },
  { emoji: '\uD83D\uDE80', ionicon: 'rocket-outline', color: '#6366f1', label: 'Ascend' },
  { emoji: '\uD83C\uDF89', ionicon: 'happy-outline', color: '#f43e5e', label: 'Joy' },
  { emoji: '\uD83D\uDC94', ionicon: 'heart-dislike-outline', color: '#ef4444', label: 'Grief' },
  { emoji: '\uD83D\uDE22', ionicon: 'sad-outline', color: '#3b82f6', label: 'Tears' },
  { emoji: '\uD83D\uDE28', ionicon: 'alert-outline', color: '#f59e0b', label: 'Awe' },
  { emoji: '\uD83D\uDE31', ionicon: 'alert-circle-outline', color: '#ef4444', label: 'Terror' },
  { emoji: '\uD83D\uDE0C', ionicon: 'happy-outline', color: '#10b981', label: 'Relief' },
  { emoji: '\uD83D\uDE07', ionicon: 'happy-outline', color: '#fbbf24', label: 'Blessed' },
  { emoji: '\uD83E\uDD72', ionicon: 'happy-outline', color: '#14b8a6', label: 'Grateful' },
  { emoji: '\uD83E\uDDD8', ionicon: 'body-outline', color: '#a855f7', label: 'Reflect' },
  { emoji: '\uD83D\uDC41\uFE0F', ionicon: 'eye-outline', color: '#3b82f6', label: 'Witness' },
  { emoji: '\uD83D\uDC42', ionicon: 'ear-outline', color: '#D4AF37', label: 'Listen' },
  { emoji: '\uD83D\uDD90\uFE0F', ionicon: 'hand-right-outline', color: '#f5f5f0', label: 'Pledge' },
  // 211–250: Landscapes & Places
  { emoji: '\uD83C\uDFD4\uFE0F', ionicon: 'trail-sign-outline', color: '#22c55e', label: 'Valley' },
  { emoji: '\uD83C\uDFD5\uFE0F', ionicon: 'bonfire-outline', color: '#84cc16', label: 'Camp' },
  { emoji: '\uD83C\uDFD6\uFE0F', ionicon: 'sunny-outline', color: '#fbbf24', label: 'Beach' },
  { emoji: '\uD83C\uDFDC\uFE0F', ionicon: 'sunny-outline', color: '#D4AF37', label: 'Desert' },
  { emoji: '\uD83C\uDFDE\uFE0F', ionicon: 'image-outline', color: '#22c55e', label: 'Meadow' },
  { emoji: '\uD83C\uDFDD\uFE0F', ionicon: 'image-outline', color: '#84cc16', label: 'Island' },
  { emoji: '\uD83C\uDFD9\uFE0F', ionicon: 'business-outline', color: '#94a3b8', label: 'City' },
  { emoji: '\uD83C\uDFE0', ionicon: 'home-outline', color: '#fb923c', label: 'Home' },
  { emoji: '\uD83C\uDFE1', ionicon: 'home-outline', color: '#22c55e', label: 'House' },
  { emoji: '\uD83C\uDFEF', ionicon: 'business-outline', color: '#D4AF37', label: 'Palace' },
  { emoji: '\uD83C\uDFEB', ionicon: 'school-outline', color: '#3b82f6', label: 'School' },
  { emoji: '\uD83C\uDFE5', ionicon: 'medkit-outline', color: '#ef4444', label: 'Healing' },
  { emoji: '\uD83C\uDFAA', ionicon: 'flag-outline', color: '#fb923c', label: 'Tent' },
  { emoji: '\u26FA', ionicon: 'triangle-outline', color: '#84cc16', label: 'Shelter' },
  { emoji: '\uD83D\uDEE4\uFE0F', ionicon: 'trail-sign-outline', color: '#78716c', label: 'Road' },
  { emoji: '\uD83D\uDEB6', ionicon: 'walk-outline', color: '#a3a398', label: 'Journey' },
  { emoji: '\uD83D\uDEF6', ionicon: 'boat-outline', color: '#06b6d4', label: 'Canoe' },
  { emoji: '\u26F5', ionicon: 'boat-outline', color: '#3b82f6', label: 'Sail' },
  { emoji: '\uD83D\uDDFA\uFE0F', ionicon: 'map-outline', color: '#D4AF37', label: 'Map' },
  { emoji: '\uD83E\uDDED', ionicon: 'compass-outline', color: '#14b8a6', label: 'Compass' },
  { emoji: '\uD83D\uDDFB', ionicon: 'triangle-outline', color: '#94a3b8', label: 'Peak' },
  { emoji: '\uD83D\uDDFC', ionicon: 'business-outline', color: '#D4AF37', label: 'Tower' },
  { emoji: '\uD83C\uDF09', ionicon: 'business-outline', color: '#6366f1', label: 'Bridge' },
  { emoji: '\uD83D\uDEA7', ionicon: 'construct-outline', color: '#fb923c', label: 'Build' },
  { emoji: '\u2618\uFE0F', ionicon: 'leaf-outline', color: '#22c55e', label: 'Clover' },
  { emoji: '\uD83C\uDF3E', ionicon: 'leaf-outline', color: '#D4AF37', label: 'Field' },
  { emoji: '\uD83C\uDFF0', ionicon: 'business-outline', color: '#a855f7', label: 'Fortress' },
  { emoji: '\uD83D\uDD73\uFE0F', ionicon: 'ellipse-outline', color: '#334155', label: 'Cave' },
  { emoji: '\uD83E\uDEA8', ionicon: 'square-outline', color: '#78716c', label: 'Stone' },
  { emoji: '\uD83E\uDEB5', ionicon: 'log-out-outline', color: '#D4AF37', label: 'Wood' },
  // 251–286: Misc & Abstract
  { emoji: '\uD83D\uDD25', ionicon: 'flame', color: '#f43e5e', label: 'Hellfire' },
  { emoji: '\uD83C\uDF4A', ionicon: 'ellipse-outline', color: '#D4AF37', label: 'Gold' },
  { emoji: '\uD83D\uDC8E', ionicon: 'diamond-outline', color: '#06b6d4', label: 'Gem' },
  { emoji: '\uD83D\uDD36', ionicon: 'diamond-outline', color: '#fb923c', label: 'Diamond' },
  { emoji: '\uD83D\uDD37', ionicon: 'diamond-outline', color: '#3b82f6', label: 'Sapphire' },
  { emoji: '\u26AA', ionicon: 'ellipse-outline', color: '#f5f5f0', label: 'Pearl' },
  { emoji: '\uD83D\uDD34', ionicon: 'ellipse-outline', color: '#ef4444', label: 'Ruby' },
  { emoji: '\uD83D\uDFE1', ionicon: 'ellipse-outline', color: '#fbbf24', label: 'Topaz' },
  { emoji: '\uD83D\uDFE2', ionicon: 'ellipse-outline', color: '#10b981', label: 'Emerald' },
  { emoji: '\uD83D\uDFE3', ionicon: 'ellipse-outline', color: '#a855f7', label: 'Amethyst' },
  { emoji: '\u2B1B', ionicon: 'square-outline', color: '#334155', label: 'Onyx' },
  { emoji: '\uD83D\uDD33', ionicon: 'diamond-outline', color: '#f5f5f0', label: 'Crystal' },
  { emoji: '\u269B\uFE0F', ionicon: 'globe-outline', color: '#06b6d4', label: 'Atom' },
  { emoji: '\u267E\uFE0F', ionicon: 'infinite-outline', color: '#a855f7', label: 'Eternal' },
  { emoji: '\u2660\uFE0F', ionicon: 'shield-outline', color: '#334155', label: 'Iron' },
  { emoji: '\u2618\uFE0F', ionicon: 'leaf-outline', color: '#10b981', label: 'Herb' },
  { emoji: '\uD83D\uDD2E', ionicon: 'globe-outline', color: '#a855f7', label: 'Sphere' },
  { emoji: '\uD83C\uDFA8', ionicon: 'color-palette-outline', color: '#f43e5e', label: 'Color' },
  { emoji: '\uD83C\uDFB6', ionicon: 'musical-notes-outline', color: '#6366f1', label: 'Melody' },
  { emoji: '\uD83D\uDCAC', ionicon: 'chatbubble-outline', color: '#94a3b8', label: 'Speech' },
  { emoji: '\uD83D\uDD17', ionicon: 'link-outline', color: '#3b82f6', label: 'Bond' },
  { emoji: '\u2699\uFE0F', ionicon: 'settings-outline', color: '#78716c', label: 'Mechanism' },
  { emoji: '\uD83D\uDD2B', ionicon: 'water-outline', color: '#06b6d4', label: 'Spray' },
  { emoji: '\uD83E\uDDF2', ionicon: 'magnet-outline', color: '#ef4444', label: 'Magnet' },
  { emoji: '\uD83E\uDDF1', ionicon: 'cube-outline', color: '#fb923c', label: 'Brick' },
  { emoji: '\uD83E\uDDEA', ionicon: 'flask-outline', color: '#10b981', label: 'Elixir' },
  { emoji: '\uD83E\uDDF3', ionicon: 'briefcase-outline', color: '#D4AF37', label: 'Luggage' },
  { emoji: '\uD83C\uDF10', ionicon: 'globe-outline', color: '#14b8a6', label: 'Network' },
  { emoji: '\u2747\uFE0F', ionicon: 'sparkles-outline', color: '#D4AF37', label: 'Sparkle' },
  { emoji: '\u2733\uFE0F', ionicon: 'star-outline', color: '#10b981', label: 'Symbol' },
  { emoji: '\u2734\uFE0F', ionicon: 'star-outline', color: '#fb923c', label: 'Mark' },
  { emoji: '\u274C', ionicon: 'close-outline', color: '#ef4444', label: 'Deny' },
  { emoji: '\u2B55', ionicon: 'ellipse-outline', color: '#ef4444', label: 'Circle' },
  { emoji: '\u2757', ionicon: 'alert-outline', color: '#ef4444', label: 'Alert' },
  { emoji: '\u2753', ionicon: 'help-outline', color: '#a855f7', label: 'Question' },
  { emoji: '\u2714\uFE0F', ionicon: 'checkmark-outline', color: '#10b981', label: 'Confirm' },
  // 287–322: Extra unique icons to cover 286+
  { emoji: '\uD83D\uDEA9', ionicon: 'flag-outline', color: '#ef4444', label: 'Flag' },
  { emoji: '\uD83C\uDFAD', ionicon: 'happy-outline', color: '#fb923c', label: 'Mask' },
  { emoji: '\uD83E\uDDF5', ionicon: 'git-branch-outline', color: '#a855f7', label: 'Thread' },
  { emoji: '\uD83E\uDDF6', ionicon: 'git-branch-outline', color: '#06b6d4', label: 'Yarn' },
  { emoji: '\uD83E\uDDF9', ionicon: 'brush-outline', color: '#D4AF37', label: 'Broom' },
  { emoji: '\uD83E\uDE9C', ionicon: 'trail-sign-outline', color: '#84cc16', label: 'Ladder' },
  { emoji: '\uD83D\uDECE\uFE0F', ionicon: 'bed-outline', color: '#6366f1', label: 'Rest' },
  { emoji: '\uD83E\uDE9E', ionicon: 'eye-outline', color: '#a855f7', label: 'Mirror' },
  { emoji: '\uD83E\uDEAB', ionicon: 'exit-outline', color: '#3b82f6', label: 'Window' },
  { emoji: '\uD83D\uDEAA', ionicon: 'enter-outline', color: '#78716c', label: 'Door' },
  { emoji: '\uD83E\uDE99', ionicon: 'ellipse-outline', color: '#D4AF37', label: 'Coin' },
  { emoji: '\uD83D\uDCBF', ionicon: 'disc-outline', color: '#94a3b8', label: 'Disc' },
  { emoji: '\uD83D\uDD70\uFE0F', ionicon: 'time-outline', color: '#D4AF37', label: 'Clock' },
  { emoji: '\uD83E\uDDEF', ionicon: 'cube-outline', color: '#ef4444', label: 'Puzzle' },
  { emoji: '\uD83C\uDFB2', ionicon: 'dice-outline', color: '#f5f5f0', label: 'Chance' },
  { emoji: '\uD83E\uDE84', ionicon: 'color-wand-outline', color: '#a855f7', label: 'Wand' },
  { emoji: '\uD83D\uDCA7', ionicon: 'rainy-outline', color: '#14b8a6', label: 'Dew' },
  { emoji: '\uD83C\uDF2B\uFE0F', ionicon: 'cloud-outline', color: '#94a3b8', label: 'Mist' },
  { emoji: '\uD83E\uDEE7', ionicon: 'water-outline', color: '#3b82f6', label: 'Bubble' },
  { emoji: '\uD83E\uDEB6', ionicon: 'leaf-outline', color: '#22c55e', label: 'Fern' },
  { emoji: '\uD83E\uDEB7', ionicon: 'leaf-outline', color: '#84cc16', label: 'Lotus' },
  { emoji: '\uD83C\uDF38', ionicon: 'flower-outline', color: '#f43e5e', label: 'Sakura' },
  { emoji: '\uD83C\uDF4B', ionicon: 'sunny-outline', color: '#84cc16', label: 'Citrus' },
  { emoji: '\uD83C\uDF50', ionicon: 'nutrition-outline', color: '#84cc16', label: 'Pear' },
  { emoji: '\uD83C\uDF51', ionicon: 'nutrition-outline', color: '#fb923c', label: 'Peach' },
  { emoji: '\uD83E\uDD5D', ionicon: 'nutrition-outline', color: '#22c55e', label: 'Kiwi' },
  { emoji: '\uD83C\uDF4F', ionicon: 'nutrition-outline', color: '#10b981', label: 'Green' },
  { emoji: '\uD83E\uDD6C', ionicon: 'leaf-outline', color: '#22c55e', label: 'Greens' },
  { emoji: '\uD83C\uDF36\uFE0F', ionicon: 'flame-outline', color: '#f43e5e', label: 'Spice' },
  { emoji: '\uD83E\uDD4B', ionicon: 'cafe-outline', color: '#06b6d4', label: 'Cup' },
  { emoji: '\uD83C\uDFB5', ionicon: 'musical-note-outline', color: '#a855f7', label: 'Note' },
  { emoji: '\uD83D\uDCA8', ionicon: 'leaf-outline', color: '#94a3b8', label: 'Breeze' },
  { emoji: '\uD83E\uDEBB', ionicon: 'flower-outline', color: '#f43e5e', label: 'Hyacinth' },
  { emoji: '\uD83E\uDD9F', ionicon: 'paw-outline', color: '#D4AF37', label: 'Llama' },
  { emoji: '\uD83E\uDD8E', ionicon: 'paw-outline', color: '#22c55e', label: 'Lizard' },
  { emoji: '\uD83E\uDD9D', ionicon: 'paw-outline', color: '#78716c', label: 'Raccoon' },
];

// ============ Core Functions ============

function stripBrackets(text: string): string {
  return text.replace(/[\[\](){}]/g, '').trim().toLowerCase();
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function getUniqueIcon(ayahNumber: number): { emoji: string; ionicon: string; color: string; label: string } {
  return UNIQUE_ICONS[(ayahNumber - 1) % UNIQUE_ICONS.length];
}

export function selectAnchorWords(ayah: Ayah): AnchorWord[] {
  return ayah.words.map(word => ({
    arabic: word.text,
    transliteration: word.transliteration,
    meaning: capitalize(stripBrackets(word.translation) || '-'),
  }));
}

export function buildAyahScene(ayah: Ayah): AyahScene {
  const icon = getUniqueIcon(ayah.ayahNumber);
  const element: VisualElement = {
    emoji: icon.emoji,
    ionicon: icon.ionicon,
    color: icon.color,
    label: icon.label,
    priority: 10,
    category: 'unique',
  };

  const anchorWords = selectAnchorWords(ayah);

  return {
    elements: [element],
    dominantColor: icon.color,
    accentColor: icon.color,
    anchorWords,
    sceneSummary: icon.label,
  };
}
